services:
  - type: web
    name: gridwise-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: FRONTEND_URL
        sync: false
      - key: DAGSHUB_USER_TOKEN
        sync: false
