export type SimulationScenario =
  | "ACCIDENT_CASCADE"
  | "STADIUM_EVENT_EGRESS"
  | "CUSTOM_INCIDENT"
  | "HISTORICAL_REPLAY"
  | "LIVE_REPLAY";

export const SIMULATION_SCENARIOS: Record<SimulationScenario, SimulationScenario> = {
  ACCIDENT_CASCADE: "ACCIDENT_CASCADE",
  STADIUM_EVENT_EGRESS: "STADIUM_EVENT_EGRESS",
  CUSTOM_INCIDENT: "CUSTOM_INCIDENT",
  HISTORICAL_REPLAY: "HISTORICAL_REPLAY",
  LIVE_REPLAY: "LIVE_REPLAY",
} as const;
