"""Initial database creation

Revision ID: e53cf96c168e
Revises: d51b6e009ba0
Create Date: 2026-06-16 14:00:26.420896

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e53cf96c168e"
down_revision: str | None = "d51b6e009ba0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
