"""Initial database creation

Revision ID: d51b6e009ba0
Revises:
Create Date: 2026-06-16 13:51:16.289366

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d51b6e009ba0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("event_category", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("junction_name", sa.String(), nullable=True),
        sa.Column("zone_name", sa.String(), nullable=True),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("road_closure", sa.Boolean(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("police_station", sa.String(), nullable=True),
        sa.Column("assigned_officer_count", sa.Integer(), nullable=False),
        sa.Column("metadata_info", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_events_event_category"), "events", ["event_category"], unique=False
    )
    op.create_index(
        op.f("ix_events_event_type"), "events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_events_severity"), "events", ["severity"], unique=False)
    op.create_index(op.f("ix_events_status"), "events", ["status"], unique=False)
    op.create_index(op.f("ix_events_zone_name"), "events", ["zone_name"], unique=False)
    op.create_table(
        "congestions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("congestion_score", sa.Float(), nullable=False),
        sa.Column("predicted_delay_minutes", sa.Integer(), nullable=False),
        sa.Column("impact_radius_km", sa.Float(), nullable=False),
        sa.Column("affected_routes", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("congestion_level", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_congestions_event_id"), "congestions", ["event_id"], unique=False
    )
    op.create_table(
        "police_deployments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("police_station", sa.String(), nullable=False),
        sa.Column("officer_count", sa.Integer(), nullable=False),
        sa.Column("barricade_count", sa.Integer(), nullable=False),
        sa.Column("deployment_status", sa.String(), nullable=False),
        sa.Column("deployed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_police_deployments_event_id"),
        "police_deployments",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_police_deployments_police_station"),
        "police_deployments",
        ["police_station"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_police_deployments_police_station"), table_name="police_deployments"
    )
    op.drop_index(
        op.f("ix_police_deployments_event_id"), table_name="police_deployments"
    )
    op.drop_table("police_deployments")
    op.drop_index(op.f("ix_congestions_event_id"), table_name="congestions")
    op.drop_table("congestions")
    op.drop_index(op.f("ix_events_zone_name"), table_name="events")
    op.drop_index(op.f("ix_events_status"), table_name="events")
    op.drop_index(op.f("ix_events_severity"), table_name="events")
    op.drop_index(op.f("ix_events_event_type"), table_name="events")
    op.drop_index(op.f("ix_events_event_category"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
