"""Simulation constants."""

from enum import Enum


class ScenarioType(str, Enum):
    ACCIDENT_CASCADE = "ACCIDENT_CASCADE"
    STADIUM_EVENT_EGRESS = "STADIUM_EVENT_EGRESS"
    CUSTOM_INCIDENT = "CUSTOM_INCIDENT"
    HISTORICAL_REPLAY = "HISTORICAL_REPLAY"
    LIVE_REPLAY = "LIVE_REPLAY"


# Timeline defaults
DEFAULT_TIMELINE_STEPS = 15
TIMELINE_STEP_MINUTES = 5

# Risk levels
RISK_LOW = "LOW"
RISK_MEDIUM = "MEDIUM"
RISK_HIGH = "HIGH"
RISK_CRITICAL = "CRITICAL"
